#!/usr/bin/env bash
#install load balancer

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 4380-lb-01
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 4380-web-01 54.167.116.248 check
	server 4380-web-02 50.17.74.91 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
